"""
Pass 2 — Deep targeted scrape (ratings 1/2/3 only) on promising URLs.

Reads URL list from promising_urls.txt (generated by quick_check_new_urls.py).
Falls back to ALL new URLs from link.txt if the file is absent.

Outputs:
  data/raw/tokopedia_reviews_low_ratings_new.csv   — new low-rating reviews

After this run, merge with existing data and re-run notebooks/02_cleaning.ipynb.
"""
import sys
import time
from pathlib import Path
import pandas as pd

sys.path.insert(0, ".")
from src.scraping.runner import run_scraper


NEW_SECTION_MARKER = "# ===== NEW URLs - Added 2026-03-12"


def chunked(items: list, size: int):
    for index in range(0, len(items), size):
        yield items[index:index + size]


def load_urls_from_file(path: str) -> list:
    p = Path(path)
    if not p.exists():
        return []
    return [
        line.strip()
        for line in p.read_text(encoding="utf-8").splitlines()
        if line.strip().startswith("http")
    ]


def load_new_urls_from_link_txt(path: str = "link.txt") -> list:
    text = Path(path).read_text(encoding="utf-8")
    idx = text.find(NEW_SECTION_MARKER)
    section = text[idx:] if idx != -1 else text
    return list(dict.fromkeys(
        line.strip()
        for line in section.splitlines()
        if line.strip().startswith("http")
    ))


def main():
    # Try to load promising_urls.txt first; fall back to full new-URL list
    promising_path = "promising_urls.txt"
    urls = load_urls_from_file(promising_path)

    if urls:
        print(f"Loaded {len(urls)} promising URLs from {promising_path}")
    else:
        urls = load_new_urls_from_link_txt("link.txt")
        print(f"promising_urls.txt not found — scanning all {len(urls)} new URLs")

    if not urls:
        print("No URLs to process"); return

    print(f"Running DEEP scan: ratings [1,2,3], max 500 reviews per URL")
    print(f"Estimated time: {len(urls) * 3}–{len(urls) * 6} minutes\n")

    batch_size = 6
    cooldown_seconds = 20
    all_reviews = []
    all_errors = []

    for batch_index, batch_urls in enumerate(chunked(urls, batch_size), start=1):
        print(f"[batch {batch_index}] deep-scanning {len(batch_urls)} URLs")
        results = run_scraper(batch_urls, max_reviews=500, target_ratings=[1, 2, 3])
        all_reviews.extend(results.get("reviews", []))
        all_errors.extend(results.get("errors", []))

        if batch_index * batch_size < len(urls):
            print(f"[batch {batch_index}] cooldown {cooldown_seconds}s\n")
            time.sleep(cooldown_seconds)

    reviews = all_reviews
    print(f"\nCollected {len(reviews)} low-rating reviews total")

    if not reviews:
        print("No low-rating reviews found."); return

    df = pd.DataFrame(reviews)

    out_path = Path("data/raw/tokopedia_reviews_low_ratings_new.csv")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(out_path, index=False, encoding="utf-8-sig")

    if all_errors:
        err_path = Path("data/raw/tokopedia_reviews_low_ratings_new_errors.csv")
        pd.DataFrame(all_errors).to_csv(err_path, index=False, encoding="utf-8-sig")
        print(f"Saved errors → {err_path}")

    print(f"Saved → {out_path}")
    print(f"Rows  : {len(df)}")
    print("\nRating distribution:")
    print(df["rating"].value_counts().sort_index())
    print("\nPer-URL breakdown:")
    print(df.groupby("product_url")["rating"].value_counts().unstack(fill_value=0))

    print(f"\nNext step → run: python merge_new_low_ratings.py")


if __name__ == "__main__":
    main()
