import json

def modify_preprocessing():
    filepath = "02_preprocessing_prdect.ipynb"
    with open(filepath, 'r', encoding='utf-8') as f:
        nb = json.load(f)
    
    # Cell 1: Colab Setup (adding emoji installation)
    cell_1 = nb['cells'][1]
    cell_1_source = [
        "## 0. Google Colab Setup\n",
        "import sys, os\n",
        "\n",
        "IN_COLAB = \"google.colab\" in sys.modules\n",
        "\n",
        "if IN_COLAB:\n",
        "    print(\"Google Colab detected — mounting Drive & installing packages ...\")\n",
        "    from google.colab import drive\n",
        "    drive.mount(\"/content/drive\")\n",
        "\n",
        "    DRIVE_PROJECT = \"/content/drive/MyDrive/xai_lime_vs_shap\"\n",
        "\n",
        "    if os.path.isdir(DRIVE_PROJECT):\n",
        "        os.chdir(DRIVE_PROJECT)\n",
        "        print(f\"CWD set to: {DRIVE_PROJECT}\")\n",
        "    else:\n",
        "        print(f\"WARNING: '{DRIVE_PROJECT}' not found. Please check your Drive path.\")\n",
        "\n",
        "    !pip install -q kaggle emoji\n",
        "else:\n",
        "    print(\"Local environment detected — skipping Colab setup.\")"
    ]
    cell_1['source'] = cell_1_source

    # Cell 2: Imports & Config (adding unicodedata and StratifiedKFold)
    cell_2 = nb['cells'][2]
    cell_2_source = [
        "## 1. Imports & Config\n",
        "import os\n",
        "import re\n",
        "import warnings\n",
        "import numpy as np\n",
        "import pandas as pd\n",
        "import matplotlib.pyplot as plt\n",
        "import seaborn as sns\n",
        "from pathlib import Path\n",
        "from sklearn.model_selection import train_test_split\n",
        "from sklearn.model_selection import StratifiedKFold\n",
        "import unicodedata\n",
        "\n",
        "warnings.filterwarnings('ignore')\n",
        "SEED = 42\n",
        "np.random.seed(SEED)\n",
        "\n",
        "def find_project_root() -> Path:\n",
        "    markers = [\"data\", \"notebooks\", \"src\"]\n",
        "    candidate = Path.cwd()\n",
        "    for _ in range(3):\n",
        "        if all((candidate / m).exists() for m in markers):\n",
        "            return candidate\n",
        "        candidate = candidate.parent\n",
        "    return Path.cwd()\n",
        "\n",
        "PROJECT_ROOT = find_project_root()\n",
        "RAW_DIR     = PROJECT_ROOT / \"data\" / \"raw\"\n",
        "PROC_DIR    = PROJECT_ROOT / \"data\" / \"processed\"\n",
        "RAW_DIR.mkdir(parents=True, exist_ok=True)\n",
        "PROC_DIR.mkdir(parents=True, exist_ok=True)\n",
        "\n",
        "TEXT_COL  = \"Customer Review\"\n",
        "LABEL_COL = \"Emotion\"\n",
        "\n",
        "print(f\"Project root : {PROJECT_ROOT}\")\n",
        "print(f\"Raw dir      : {RAW_DIR}\")\n",
        "print(f\"Processed    : {PROC_DIR}\")\n",
        "print(f\"TEXT_COL     : {TEXT_COL}\")\n",
        "print(f\"LABEL_COL    : {LABEL_COL}\")"
    ]
    cell_2['source'] = cell_2_source

    # Cell 8: Text Cleaning
    cell_8 = nb['cells'][8]
    cell_8_source = [
        "## 7. Text Cleaning\n",
        "import emoji\n",
        "\n",
        "# Slang Dictionary (Top 30-40 Indonesian Review Slang Words)\n",
        "SLANG_MAP = {\n",
        "    \"yg\": \"yang\",\n",
        "    \"ga\": \"tidak\",\n",
        "    \"gak\": \"tidak\",\n",
        "    \"gk\": \"tidak\",\n",
        "    \"ngga\": \"tidak\",\n",
        "    \"nggak\": \"tidak\",\n",
        "    \"bgt\": \"banget\",\n",
        "    \"dgn\": \"dengan\",\n",
        "    \"kalo\": \"kalau\",\n",
        "    \"jgn\": \"jangan\",\n",
        "    \"tp\": \"tapi\",\n",
        "    \"sm\": \"sama\",\n",
        "    \"sdh\": \"sudah\",\n",
        "    \"krn\": \"karena\",\n",
        "    \"utk\": \"untuk\",\n",
        "    \"sy\": \"saya\",\n",
        "    \"td\": \"tadi\",\n",
        "    \"smg\": \"semoga\",\n",
        "    \"blm\": \"belum\",\n",
        "    \"jd\": \"jadi\",\n",
        "    \"aja\": \"saja\",\n",
        "    \"dah\": \"sudah\",\n",
        "    \"udh\": \"sudah\",\n",
        "    \"gw\": \"saya\",\n",
        "    \"gua\": \"saya\",\n",
        "    \"lu\": \"kamu\",\n",
        "    \"elo\": \"kamu\",\n",
        "    \"msh\": \"masih\",\n",
        "    \"skrg\": \"sekarang\",\n",
        "    \"dpt\": \"dapat\",\n",
        "    \"dr\": \"dari\",\n",
        "    \"km\": \"kamu\",\n",
        "    \"pake\": \"pakai\",\n",
        "    \"karna\": \"karena\",\n",
        "    \"g\": \"tidak\",\n",
        "}\n",
        "\n",
        "def clean_text(text: str) -> str:\n",
        "    \"\"\"Unicode normalisation, safe character cleaning, emoji demojizing, and slang normalization.\"\"\"\n",
        "    if not isinstance(text, str):\n",
        "        return \"\"\n",
        "    \n",
        "    # 1. Unicode Normalization\n",
        "    text = unicodedata.normalize('NFKC', text)\n",
        "    \n",
        "    # 2. Safe removal of corrupted character U+FFFD\n",
        "    text = text.replace('\\ufffd', ' ')\n",
        "    \n",
        "    # 3. Emoji Demojization (e.g. 😂 -> :face_with_tears_of_joy:)\n",
        "    try:\n",
        "        text = emoji.demojize(text)\n",
        "    except Exception:\n",
        "        pass\n",
        "    \n",
        "    text = text.lower()\n",
        "    \n",
        "    # 4. Remove URL and mentions\n",
        "    text = re.sub(r'https?://\\S+|www\\.\\S+', ' ', text)\n",
        "    text = re.sub(r'@[\\w_]+', ' ', text)\n",
        "    \n",
        "    # 5. Clean punctuation but preserve spaces, !?., and emoji delimiters (: and _)\n",
        "    text = re.sub(r'[^a-zA-Z0-9\\s!?.,:_]', ' ', text)\n",
        "    \n",
        "    # 6. Slang normalization (word-by-word replacement)\n",
        "    words = text.split()\n",
        "    normalized_words = []\n",
        "    for w in words:\n",
        "        clean_w = re.sub(r'[^a-zA-Z0-9]', '', w)\n",
        "        if clean_w in SLANG_MAP:\n",
        "            if w.startswith(':') and w.endswith(':'):\n",
        "                normalized_words.append(w)  # Keep emoji text intact\n",
        "            else:\n",
        "                normalized_words.append(SLANG_MAP[clean_w])\n",
        "        else:\n",
        "            normalized_words.append(w)\n",
        "    text = \" \".join(normalized_words)\n",
        "    \n",
        "    # 7. Convert emoji text separators to spaces (e.g. :face_with_tears_of_joy: -> face with tears of joy)\n",
        "    text = text.replace(':', ' ').replace('_', ' ')\n",
        "    \n",
        "    # 8. Clean up whitespace and repeated punctuation\n",
        "    text = re.sub(r'([!?.,]){2,}', r'\\1', text)\n",
        "    text = re.sub(r'\\s+', ' ', text).strip()\n",
        "    return text\n",
        "\n",
        "# Contoh cleaning\n",
        "sample_text = df[TEXT_COL].iloc[0]\n",
        "print(f\"Original : {repr(sample_text)}\")\n",
        "print(f\"Cleaned  : {repr(clean_text(sample_text))}\")"
    ]
    cell_8['source'] = cell_8_source

    # Cell 9: Apply Cleaning, Label Mapping & Deduplication with conflicting audit
    cell_9 = nb['cells'][9]
    cell_9_source = [
        "## 8. Apply Cleaning, Label Mapping & Deduplication\n",
        "EMOTION_MAP = {\n",
        "    'happy'  : 0,\n",
        "    'love'   : 1,\n",
        "    'anger'  : 2,\n",
        "    'fear'   : 3,\n",
        "    'sadness': 4,\n",
        "}\n",
        "ID2EMOTION = {v: k for k, v in EMOTION_MAP.items()}\n",
        "\n",
        "# Normalize label\n",
        "df['emotion_label'] = df[LABEL_COL].str.lower().str.strip()\n",
        "\n",
        "# Apply mapping\n",
        "df['label'] = df['emotion_label'].map(EMOTION_MAP)\n",
        "df = df.dropna(subset=['label'])\n",
        "\n",
        "# --- 1. Audit Conflicting Labels ---\n",
        "duplicate_mask = df.duplicated(subset=[TEXT_COL], keep=False)\n",
        "duplicates_df = df[duplicate_mask]\n",
        "\n",
        "conflicting_texts = []\n",
        "grouped_dupes = duplicates_df.groupby(TEXT_COL)\n",
        "for text, group in grouped_dupes:\n",
        "    if group['label'].nunique() > 1:\n",
        "        conflicting_texts.append(text)\n",
        "\n",
        "conflicting_df = duplicates_df[duplicates_df[TEXT_COL].isin(conflicting_texts)].copy()\n",
        "\n",
        "# Save conflicting labels report for manual review\n",
        "reports_dir = Path(\"outputs/finetuning_indobert/reports\")\n",
        "reports_dir.mkdir(parents=True, exist_ok=True)\n",
        "conflicting_out = reports_dir / \"conflicting_labels.csv\"\n",
        "conflicting_df[[TEXT_COL, 'Emotion', 'Customer Rating']].to_csv(conflicting_out, index=False)\n",
        "print(f\"Saved conflicting labels report ({len(conflicting_df)} rows) to: {conflicting_out}\")\n",
        "\n",
        "# --- 2. Deduplicate (keep the first occurrence) ---\n",
        "before = len(df)\n",
        "df = df.drop_duplicates(subset=[TEXT_COL], keep='first').copy()\n",
        "print(f\"Deduplicated: {before} -> {len(df)} rows ({before - len(df)} duplicate rows removed)\")\n",
        "\n",
        "# Apply text cleaning\n",
        "df['review_clean'] = df[TEXT_COL].apply(clean_text)\n",
        "\n",
        "# Hapus baris kosong\n",
        "before_empty = len(df)\n",
        "df = df.dropna(subset=['review_clean'])\n",
        "df = df[df['review_clean'].str.strip().str.len() > 3]\n",
        "after_empty = len(df)\n",
        "df['label'] = df['label'].astype(int)\n",
        "\n",
        "print(f\"Data setelah filter teks kosong: {before_empty} -> {after_empty} ({before_empty - after_empty} dihapus)\")\n",
        "print(f\"\\nDistribusi final:\")\n",
        "print(df['emotion_label'].value_counts())"
    ]
    cell_9['source'] = cell_9_source

    # Cell 10: Stratified Split & Stratified K-Fold
    cell_10 = nb['cells'][10]
    cell_10_source = [
        "## 9. Stratified Split (80% Train / 20% Test) & Stratified K-Fold\n",
        "# Split into Train and Test\n",
        "df_train, df_test = train_test_split(\n",
        "    df, test_size=0.2, random_state=SEED, stratify=df['label']\n",
        ")\n",
        "\n",
        "# Add Stratified 5-Fold split to the training set for cross-validation\n",
        "skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED)\n",
        "df_train['fold'] = -1\n",
        "for fold_idx, (train_idx, val_idx) in enumerate(skf.split(df_train, df_train['label'])):\n",
        "    # Set validation indices for this fold to fold_idx\n",
        "    df_train.loc[df_train.index[val_idx], 'fold'] = fold_idx\n",
        "\n",
        "print(f\"Train size: {len(df_train)}\")\n",
        "print(f\"Test size : {len(df_test)}\")\n",
        "\n",
        "print(\"\\nFold distribution in Train:\")\n",
        "print(df_train.groupby(['fold', 'emotion_label']).size().unstack(fill_value=0))"
    ]
    cell_10['source'] = cell_10_source

    # Cell 11: Export Data
    cell_11 = nb['cells'][11]
    cell_11_source = [
        "## 10. Export Data\n",
        "import json\n",
        "\n",
        "# Export cleaned full dataset\n",
        "clean_out = PROC_DIR / \"prdect_clean.csv\"\n",
        "df[['review_clean', 'emotion_label', 'label']].to_csv(clean_out, index=False)\n",
        "print(f\"Saved: {clean_out}\")\n",
        "\n",
        "# Export train/test split (including fold in train)\n",
        "train_out = PROC_DIR / \"prdect_train.csv\"\n",
        "test_out  = PROC_DIR / \"prdect_test.csv\"\n",
        "df_train[['review_clean', 'emotion_label', 'label', 'fold']].to_csv(train_out, index=False)\n",
        "df_test[['review_clean', 'emotion_label', 'label']].to_csv(test_out, index=False)\n",
        "print(f\"Saved: {train_out}\")\n",
        "print(f\"Saved: {test_out}\")\n",
        "\n",
        "# Export label map\n",
        "label_map_out = PROC_DIR / \"prdect_label_map.json\"\n",
        "with open(label_map_out, 'w') as f:\n",
        "    json.dump({\"label2id\": EMOTION_MAP, \"id2label\": ID2EMOTION}, f, indent=2)\n",
        "print(f\"Saved: {label_map_out}\")\n",
        "\n",
        "print(\"\\n=== Summary ===\")\n",
        "print(f\"Full dataset : {len(df)} rows\")\n",
        "print(f\"Train set    : {len(df_train)} rows\")\n",
        "print(f\"Test set     : {len(df_test)} rows\")\n",
        "print(f\"Label mapping: {EMOTION_MAP}\")"
    ]
    cell_11['source'] = cell_11_source

    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(nb, f, indent=1, ensure_ascii=False)
    print("Successfully modified preprocessing notebook!")

modify_preprocessing()
