import json

def modify_training():
    filepath = "02_finetuning_indobert_emotion2.ipynb"
    with open(filepath, 'r', encoding='utf-8') as f:
        nb = json.load(f)
    
    # Cell 2: Config and Hyperparameters
    cell_2 = nb['cells'][2]
    cell_2_source = [
        "import os\n",
        "import random\n",
        "import json\n",
        "import time\n",
        "import math\n",
        "import shutil\n",
        "import pandas as pd\n",
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "import seaborn as sns\n",
        "from tqdm.auto import tqdm\n",
        "from datetime import datetime\n",
        "from pathlib import Path\n",
        "\n",
        "import torch\n",
        "import torch.nn as nn\n",
        "from torch.utils.data import Dataset, DataLoader\n",
        "from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, f1_score, precision_score, recall_score, precision_recall_fscore_support\n",
        "from sklearn.model_selection import train_test_split\n",
        "from transformers import AutoTokenizer, BertForSequenceClassification, get_linear_schedule_with_warmup\n",
        "from torch.optim import AdamW\n",
        "\n",
        "# --- Reproducibility ---\n",
        "RANDOM_STATE = 42\n",
        "def set_seed(seed):\n",
        "    random.seed(seed)\n",
        "    np.random.seed(seed)\n",
        "    torch.manual_seed(seed)\n",
        "    torch.cuda.manual_seed_all(seed)\n",
        "    os.environ['PYTHONHASHSEED'] = str(seed)\n",
        "    torch.backends.cudnn.deterministic = True\n",
        "    torch.backends.cudnn.benchmark = False\n",
        "\n",
        "set_seed(RANDOM_STATE)\n",
        "\n",
        "# --- Hyperparameters ---\n",
        "MODEL_NAME = \"indobenchmark/indobert-base-p2\"\n",
        "MAX_LEN = 128\n",
        "BATCH_SIZE = 16\n",
        "EPOCHS = 10\n",
        "PATIENCE = 3\n",
        "NUM_LABELS = 5\n",
        "WEIGHT_DECAY = 0.02  # Set default weight decay in 0.01-0.03 range\n",
        "WARMUP_RATIO = 0.1\n",
        "LABEL_SMOOTHING = 0.1\n",
        "CLASSIFIER_DROPOUT = 0.3  # Set default classifier dropout to 0.3\n",
        "\n",
        "# Learning rate experiments\n",
        "LR_EXPERIMENTS = [1e-5, 2e-5, 3e-5, 5e-5]\n",
        "SELECTED_LR = 2e-5\n",
        "\n",
        "# --- Path Configuration ---\n",
        "try:\n",
        "    from google.colab import drive\n",
        "    IN_COLAB = True\n",
        "except ImportError:\n",
        "    IN_COLAB = False\n",
        "\n",
        "if IN_COLAB:\n",
        "    print(\"Running in Google Colab. Mounting Drive...\")\n",
        "    drive.mount('/content/drive')\n",
        "    BASE_PATH = \"/content/drive/MyDrive/xai_lime_vs_shap\"\n",
        "else:\n",
        "    print(\"Running locally.\")\n",
        "    BASE_PATH = \".\"\n",
        "\n",
        "TRAIN_DATA_PATH = f\"{BASE_PATH}/data/processed/prdect_train.csv\"\n",
        "TEST_DATA_PATH = f\"{BASE_PATH}/data/processed/prdect_test.csv\"\n",
        "MAPPING_PATH = f\"{BASE_PATH}/data/processed/prdect_label_map.json\"\n",
        "OUTPUT_DIR = f\"{BASE_PATH}/outputs/finetuning_indobert\"\n",
        "\n",
        "os.makedirs(OUTPUT_DIR, exist_ok=True)\n",
        "os.makedirs(f\"{OUTPUT_DIR}/model\", exist_ok=True)\n",
        "os.makedirs(f\"{OUTPUT_DIR}/plots\", exist_ok=True)\n",
        "os.makedirs(f\"{OUTPUT_DIR}/reports\", exist_ok=True)\n",
        "os.makedirs(f\"{OUTPUT_DIR}/tokenizer\", exist_ok=True)\n",
        "\n",
        "DEVICE = torch.device(\"cuda\" if torch.cuda.is_available() else \"cpu\")\n",
        "print(f\"Device used: {DEVICE}\")\n",
        "print(f\"Model name : {MODEL_NAME}\")\n",
        "\n",
        "# --- Data loading helpers ---\n",
        "if not os.path.exists(MAPPING_PATH):\n",
        "    MAPPING_PATH = f\"{BASE_PATH}/data/processed/prdect_label_mapping.json\"\n",
        "\n",
        "LABEL_ORDER = ['happy', 'love', 'anger', 'fear', 'sadness']\n",
        "EMOTION_MAP = {label: idx for idx, label in enumerate(LABEL_ORDER)}\n",
        "ID2EMOTION = {idx: label for label, idx in EMOTION_MAP.items()}"
    ]
    cell_2['source'] = cell_2_source

    # Cell 4: Load Processed Dataset
    cell_4 = nb['cells'][4]
    cell_4_source = [
        "df_train = pd.read_csv(TRAIN_DATA_PATH)\n",
        "df_test = pd.read_csv(TEST_DATA_PATH)\n",
        "\n",
        "with open(MAPPING_PATH, 'r') as f:\n",
        "    label_mapping = json.load(f)\n",
        "\n",
        "print(f\"Train samples: {len(df_train)}\")\n",
        "print(f\"Test samples : {len(df_test)}\")\n",
        "print(\"-\" * 30)\n",
        "print(\"Label Mapping:\")\n",
        "print(label_mapping)\n",
        "\n",
        "# Normalize schema from preprocessing output\n",
        "text_column = 'review_clean' if 'review_clean' in df_train.columns else 'Customer Review'\n",
        "label_name_column = 'emotion_label' if 'emotion_label' in df_train.columns else 'Emotion'\n",
        "label_id_column = 'label' if 'label' in df_train.columns else 'Label'\n",
        "fold_column = 'fold' if 'fold' in df_train.columns else 'Fold'\n",
        "\n",
        "train_df = df_train[[text_column, label_name_column, label_id_column, fold_column]].copy()\n",
        "test_df = df_test[[text_column, label_name_column, label_id_column]].copy()\n",
        "\n",
        "train_df.columns = ['text', 'emotion_label', 'label', 'fold']\n",
        "test_df.columns = ['text', 'emotion_label', 'label']\n",
        "\n",
        "train_df['emotion_label'] = train_df['emotion_label'].astype(str).str.lower().str.strip()\n",
        "test_df['emotion_label'] = test_df['emotion_label'].astype(str).str.lower().str.strip()\n",
        "train_df['label'] = train_df['label'].astype(int)\n",
        "test_df['label'] = test_df['label'].astype(int)\n",
        "train_df['fold'] = train_df['fold'].astype(int)\n",
        "\n",
        "train_df = train_df.reset_index(drop=True)\n",
        "test_df = test_df.reset_index(drop=True)\n",
        "\n",
        "print(f\"Train set    : {len(train_df)}\")\n",
        "print(f\"Test set     : {len(test_df)}\")\n",
        "print(\"Fold distribution in Train:\")\n",
        "print(train_df.groupby(['fold', 'emotion_label']).size().unstack(fill_value=0))"
    ]
    cell_4['source'] = cell_4_source

    # Cell 8: Dataset & DataLoader (removing class weights initialization, keeping loader definition)
    cell_8 = nb['cells'][8]
    cell_8_source = [
        "class EmotionDataset(Dataset):\n",
        "    def __init__(self, reviews, labels, tokenizer, max_len):\n",
        "        self.reviews = reviews\n",
        "        self.labels = labels\n",
        "        self.tokenizer = tokenizer\n",
        "        self.max_len = max_len\n",
        "\n",
        "    def __len__(self):\n",
        "        return len(self.reviews)\n",
        "\n",
        "    def __getitem__(self, item):\n",
        "        review = str(self.reviews[item])\n",
        "        label = int(self.labels[item])\n",
        "\n",
        "        encoding = self.tokenizer(\n",
        "            review,\n",
        "            add_special_tokens=True,\n",
        "            max_length=self.max_len,\n",
        "            return_token_type_ids=False,\n",
        "            padding='max_length',\n",
        "            truncation=True,\n",
        "            return_attention_mask=True,\n",
        "            return_tensors='pt',\n",
        "        )\n",
        "\n",
        "        return {\n",
        "            'review_text': review,\n",
        "            'input_ids': encoding['input_ids'].flatten(),\n",
        "            'attention_mask': encoding['attention_mask'].flatten(),\n",
        "            'labels': torch.tensor(label, dtype=torch.long)\n",
        "        }\n",
        "\n",
        "def create_data_loader(df, tokenizer, max_len, batch_size, shuffle=True):\n",
        "    ds = EmotionDataset(\n",
        "        reviews=df['text'].to_numpy(),\n",
        "        labels=df['label'].to_numpy(),\n",
        "        tokenizer=tokenizer,\n",
        "        max_len=max_len\n",
        "    )\n",
        "    return DataLoader(ds, batch_size=batch_size, shuffle=shuffle)\n",
        "\n",
        "tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)\n",
        "\n",
        "# Test data loader is global\n",
        "test_data_loader = create_data_loader(test_df, tokenizer, MAX_LEN, BATCH_SIZE, shuffle=False)"
    ]
    cell_8['source'] = cell_8_source

    # Cell 10: Model Initialization helper function
    cell_10 = nb['cells'][10]
    cell_10_source = [
        "def initialize_model(model_name, num_labels, dropout_prob):\n",
        "    model = BertForSequenceClassification.from_pretrained(\n",
        "        model_name,\n",
        "        num_labels=num_labels\n",
        "    )\n",
        "    # Set custom classification dropout\n",
        "    model.config.classifier_dropout = dropout_prob\n",
        "    model = model.to(DEVICE)\n",
        "    return model\n",
        "\n",
        "model = initialize_model(MODEL_NAME, NUM_LABELS, CLASSIFIER_DROPOUT)\n",
        "\n",
        "# Verify parameters\n",
        "trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)\n",
        "total_params = sum(p.numel() for p in model.parameters())\n",
        "print(f\"Total Parameters    : {total_params:,}\")\n",
        "print(f\"Trainable Parameters: {trainable_params:,}\")"
    ]
    cell_10['source'] = cell_10_source

    # Cell 12: Optimizer & Train functions (update loss_fn to standard cross entropy with label smoothing)
    cell_12 = nb['cells'][12]
    cell_12_source = [
        "# Standard CrossEntropyLoss with Label Smoothing (no class weights)\n",
        "loss_fn = nn.CrossEntropyLoss(label_smoothing=LABEL_SMOOTHING).to(DEVICE)\n",
        "\n",
        "def compute_metrics(y_true, y_pred):\n",
        "    acc = accuracy_score(y_true, y_pred)\n",
        "    macro_p, macro_r, macro_f1, _ = precision_recall_fscore_support(\n",
        "        y_true, y_pred, average='macro', zero_division=0\n",
        "    )\n",
        "    weighted_p, weighted_r, weighted_f1, _ = precision_recall_fscore_support(\n",
        "        y_true, y_pred, average='weighted', zero_division=0\n",
        "    )\n",
        "    return {\n",
        "        'accuracy': acc,\n",
        "        'macro_precision': macro_p,\n",
        "        'macro_recall': macro_r,\n",
        "        'macro_f1': macro_f1,\n",
        "        'weighted_precision': weighted_p,\n",
        "        'weighted_recall': weighted_r,\n",
        "        'weighted_f1': weighted_f1,\n",
        "    }\n",
        "\n",
        "def train_epoch(model, data_loader, loss_fn, optimizer, device, scheduler, n_examples):\n",
        "    model = model.train()\n",
        "    losses = []\n",
        "    correct_predictions = 0\n",
        "    all_preds = []\n",
        "    all_labels = []\n",
        "\n",
        "    progress_bar = tqdm(data_loader, desc=\"Training\")\n",
        "    for d in progress_bar:\n",
        "        input_ids = d[\"input_ids\"].to(device)\n",
        "        attention_mask = d[\"attention_mask\"].to(device)\n",
        "        labels = d[\"labels\"].to(device)\n",
        "\n",
        "        outputs = model(\n",
        "            input_ids=input_ids,\n",
        "            attention_mask=attention_mask\n",
        "        )\n",
        "\n",
        "        logits = outputs.logits\n",
        "        _, preds = torch.max(logits, dim=1)\n",
        "        loss = loss_fn(logits, labels)\n",
        "\n",
        "        correct_predictions += torch.sum(preds == labels)\n",
        "        losses.append(loss.item())\n",
        "        all_preds.extend(preds.detach().cpu().numpy().tolist())\n",
        "        all_labels.extend(labels.detach().cpu().numpy().tolist())\n",
        "\n",
        "        loss.backward()\n",
        "        nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)\n",
        "        optimizer.step()\n",
        "        scheduler.step()\n",
        "        optimizer.zero_grad()\n",
        "\n",
        "        progress_bar.set_postfix({'loss': np.mean(losses)})\n",
        "\n",
        "    metrics = compute_metrics(all_labels, all_preds)\n",
        "    return correct_predictions.double() / n_examples, np.mean(losses), metrics\n",
        "\n",
        "def eval_model(model, data_loader, loss_fn, device, n_examples):\n",
        "    model = model.eval()\n",
        "    losses = []\n",
        "    correct_predictions = 0\n",
        "    all_preds = []\n",
        "    all_labels = []\n",
        "\n",
        "    with torch.no_grad():\n",
        "        for d in data_loader:\n",
        "            input_ids = d[\"input_ids\"].to(device)\n",
        "            attention_mask = d[\"attention_mask\"].to(device)\n",
        "            labels = d[\"labels\"].to(device)\n",
        "\n",
        "            outputs = model(\n",
        "                input_ids=input_ids,\n",
        "                attention_mask=attention_mask\n",
        "            )\n",
        "\n",
        "            logits = outputs.logits\n",
        "            _, preds = torch.max(logits, dim=1)\n",
        "            loss = loss_fn(logits, labels)\n",
        "\n",
        "            correct_predictions += torch.sum(preds == labels)\n",
        "            losses.append(loss.item())\n",
        "            all_preds.extend(preds.detach().cpu().numpy().tolist())\n",
        "            all_labels.extend(labels.detach().cpu().numpy().tolist())\n",
        "\n",
        "    metrics = compute_metrics(all_labels, all_preds)\n",
        "    return correct_predictions.double() / n_examples, np.mean(losses), metrics, all_labels, all_preds"
    ]
    cell_12['source'] = cell_12_source

    # Cell 14: Execution: 5-Fold Cross Validation training loop with early stopping on val_loss
    cell_14 = nb['cells'][14]
    cell_14_source = [
        "def train_cross_validation(learning_rate):\n",
        "    print(f\"==================================================\")\n",
        "    print(f\"STARTING 5-FOLD CROSS VALIDATION WITH LR = {learning_rate}\")\n",
        "    print(f\"==================================================\")\n",
        "    \n",
        "    cv_history = []\n",
        "    start_time = time.time()\n",
        "    \n",
        "    # Placeholders for predictions on the test set across all folds\n",
        "    fold_test_probs = []\n",
        "    \n",
        "    for fold_idx in range(5):\n",
        "        print(f\"\\n--- Fold {fold_idx + 1} / 5 ---\")\n",
        "        \n",
        "        # Split train and validation dynamically based on fold column\n",
        "        fold_train_df = train_df[train_df['fold'] != fold_idx].reset_index(drop=True)\n",
        "        fold_val_df = train_df[train_df['fold'] == fold_idx].reset_index(drop=True)\n",
        "        \n",
        "        fold_train_loader = create_data_loader(fold_train_df, tokenizer, MAX_LEN, BATCH_SIZE)\n",
        "        fold_val_loader = create_data_loader(fold_val_df, tokenizer, MAX_LEN, BATCH_SIZE, shuffle=False)\n",
        "        \n",
        "        # Initialize model, optimizer, scheduler for this fold\n",
        "        fold_model = initialize_model(MODEL_NAME, NUM_LABELS, CLASSIFIER_DROPOUT)\n",
        "        fold_optimizer = AdamW(fold_model.parameters(), lr=learning_rate, weight_decay=WEIGHT_DECAY)\n",
        "        \n",
        "        total_steps = len(fold_train_loader) * EPOCHS\n",
        "        warmup_steps = max(1, int(total_steps * WARMUP_RATIO))\n",
        "        fold_scheduler = get_linear_schedule_with_warmup(\n",
        "            fold_optimizer,\n",
        "            num_warmup_steps=warmup_steps,\n",
        "            num_training_steps=total_steps\n",
        "        )\n",
        "        \n",
        "        best_val_loss = float('inf')\n",
        "        patience_counter = 0\n",
        "        fold_best_path = f\"{OUTPUT_DIR}/model/best_model_fold_{fold_idx}.bin\"\n",
        "        \n",
        "        fold_history = {\n",
        "            'epoch': [],\n",
        "            'train_loss': [], 'train_acc': [],\n",
        "            'val_loss': [], 'val_acc': []\n",
        "        }\n",
        "        \n",
        "        for epoch in range(EPOCHS):\n",
        "            print(f\"Epoch {epoch + 1}/{EPOCHS}\")\n",
        "            \n",
        "            # Train epoch\n",
        "            train_acc, train_loss, train_metrics = train_epoch(\n",
        "                fold_model, fold_train_loader, loss_fn, fold_optimizer, DEVICE, fold_scheduler, len(fold_train_df)\n",
        "            )\n",
        "            \n",
        "            # Val epoch\n",
        "            val_acc, val_loss, val_metrics, _, _ = eval_model(\n",
        "                fold_model, fold_val_loader, loss_fn, DEVICE, len(fold_val_df)\n",
        "            )\n",
        "            \n",
        "            print(\n",
        "                f\"Train loss: {train_loss:.4f} acc: {train_acc:.4f} | \"\n",
        "                f\"Val loss: {val_loss:.4f} acc: {val_acc:.4f} | \"\n",
        "                f\"Best Val Loss: {best_val_loss:.4f} | Patience: {patience_counter}/{PATIENCE}\"\n",
        "            )\n",
        "            \n",
        "            fold_history['epoch'].append(epoch + 1)\n",
        "            fold_history['train_loss'].append(train_loss)\n",
        "            fold_history['train_acc'].append(train_acc.item())\n",
        "            fold_history['val_loss'].append(val_loss)\n",
        "            fold_history['val_acc'].append(val_acc.item())\n",
        "            \n",
        "            # Early stopping monitors val_loss\n",
        "            if val_loss < best_val_loss:\n",
        "                torch.save(fold_model.state_dict(), fold_best_path)\n",
        "                best_val_loss = val_loss\n",
        "                patience_counter = 0\n",
        "            else:\n",
        "                patience_counter += 1\n",
        "                \n",
        "            if patience_counter >= PATIENCE:\n",
        "                print(f\"Early stopping triggered for Fold {fold_idx + 1} at epoch {epoch + 1}.\")\n",
        "                break\n",
        "                \n",
        "        cv_history.append(fold_history)\n",
        "        \n",
        "    end_time = time.time()\n",
        "    print(f\"\\nCross-validation completed in {(end_time - start_time)/60:.2f} minutes.\")\n",
        "    return cv_history\n",
        "\n",
        "# Execute 5-fold cross validation for the selected learning rate\n",
        "cv_results = train_cross_validation(SELECTED_LR)"
    ]
    cell_14['source'] = cell_14_source

    # Cell 16: Evaluation & Visualization (average fold probabilities to build an ensemble)
    cell_16 = nb['cells'][16]
    cell_16_source = [
        "# Plotting Training Curves across all folds\n",
        "plt.figure(figsize=(15, 10))\n",
        "for idx, fh in enumerate(cv_results):\n",
        "    plt.subplot(2, 3, idx + 1)\n",
        "    plt.plot(fh['train_loss'], label='train loss')\n",
        "    plt.plot(fh['val_loss'], label='val loss')\n",
        "    plt.title(f'Fold {idx + 1} Losses')\n",
        "    plt.xlabel('Epoch')\n",
        "    plt.ylabel('Loss')\n",
        "    plt.legend()\n",
        "plt.tight_layout()\n",
        "plt.savefig(f\"{OUTPUT_DIR}/plots/training_curves.png\")\n",
        "plt.show()\n",
        "\n",
        "def get_predictions(model, data_loader):\n",
        "    model = model.eval()\n",
        "    review_texts = []\n",
        "    predictions = []\n",
        "    prediction_probs = []\n",
        "    real_values = []\n",
        "\n",
        "    with torch.no_grad():\n",
        "        for d in data_loader:\n",
        "            texts = d[\"review_text\"]\n",
        "            input_ids = d[\"input_ids\"].to(DEVICE)\n",
        "            attention_mask = d[\"attention_mask\"].to(DEVICE)\n",
        "            labels = d[\"labels\"].to(DEVICE)\n",
        "\n",
        "            outputs = model(\n",
        "                input_ids=input_ids,\n",
        "                attention_mask=attention_mask\n",
        "            )\n",
        "\n",
        "            logits = outputs.logits\n",
        "            probs = torch.nn.functional.softmax(logits, dim=1)\n",
        "            _, preds = torch.max(logits, dim=1)\n",
        "\n",
        "            review_texts.extend(texts)\n",
        "            predictions.extend(preds.detach().cpu().tolist())\n",
        "            prediction_probs.extend(probs.detach().cpu().tolist())\n",
        "            real_values.extend(labels.detach().cpu().tolist())\n",
        "\n",
        "    predictions = torch.tensor(predictions)\n",
        "    prediction_probs = torch.tensor(prediction_probs)\n",
        "    real_values = torch.tensor(real_values)\n",
        "    return review_texts, predictions, prediction_probs, real_values\n",
        "\n",
        "# Final Evaluation on Test Set uses the ensemble of all 5 folds\n",
        "print(\"Evaluating 5-fold ensemble model on the test set...\")\n",
        "y_pred_probs_list = []\n",
        "y_test_check = None\n",
        "y_review_texts = None\n",
        "\n",
        "for fold_idx in range(5):\n",
        "    fold_model_path = f\"{OUTPUT_DIR}/model/best_model_fold_{fold_idx}.bin\"\n",
        "    fold_model = initialize_model(MODEL_NAME, NUM_LABELS, CLASSIFIER_DROPOUT)\n",
        "    fold_model.load_state_dict(torch.load(fold_model_path, map_location=DEVICE))\n",
        "    \n",
        "    review_texts, y_pred_fold, y_pred_probs_fold, y_test_fold = get_predictions(fold_model, test_data_loader)\n",
        "    y_pred_probs_list.append(y_pred_probs_fold)\n",
        "    y_test_check = y_test_fold\n",
        "    y_review_texts = review_texts\n",
        "\n",
        "# Average probabilities across the 5 folds (Ensemble prediction)\n",
        "y_pred_probs = torch.mean(torch.stack(y_pred_probs_list), dim=0)\n",
        "y_pred = torch.argmax(y_pred_probs, dim=1)\n",
        "y_test = y_test_check\n",
        "\n",
        "# Classification Report\n",
        "class_names = [ID2EMOTION[i] for i in range(NUM_LABELS)]\n",
        "report = classification_report(y_test, y_pred, target_names=class_names, digits=4, zero_division=0)\n",
        "print(report)\n",
        "report_dict = classification_report(y_test, y_pred, target_names=class_names, output_dict=True, zero_division=0)\n",
        "pd.DataFrame(report_dict).T.to_csv(f\"{OUTPUT_DIR}/reports/classification_report.csv\")\n",
        "with open(f\"{OUTPUT_DIR}/reports/classification_report.txt\", \"w\") as f:\n",
        "    f.write(report)\n",
        "\n",
        "# Confusion Matrix\n",
        "cm = confusion_matrix(y_test, y_pred)\n",
        "df_cm = pd.DataFrame(cm, index=class_names, columns=class_names)\n",
        "plt.figure(figsize=(10, 7))\n",
        "sns.heatmap(df_cm, annot=True, fmt='d', cmap='Blues')\n",
        "plt.title(\"Confusion Matrix\")\n",
        "plt.xlabel(\"Predicted\")\n",
        "plt.ylabel(\"Actual\")\n",
        "plt.savefig(f\"{OUTPUT_DIR}/plots/confusion_matrix.png\")\n",
        "plt.show()\n",
        "\n",
        "final_acc = accuracy_score(y_test, y_pred)\n",
        "final_macro_precision = precision_score(y_test, y_pred, average='macro', zero_division=0)\n",
        "final_macro_recall = recall_score(y_test, y_pred, average='macro', zero_division=0)\n",
        "final_macro_f1 = f1_score(y_test, y_pred, average='macro', zero_division=0)\n",
        "final_weighted_f1 = f1_score(y_test, y_pred, average='weighted', zero_division=0)\n",
        "\n",
        "final_metrics = {\n",
        "    'test_accuracy': final_acc,\n",
        "    'test_macro_precision': final_macro_precision,\n",
        "    'test_macro_recall': final_macro_recall,\n",
        "    'test_macro_f1': final_macro_f1,\n",
        "    'test_weighted_f1': final_weighted_f1,\n",
        "}\n",
        "with open(f\"{OUTPUT_DIR}/reports/test_metrics.json\", \"w\") as f:\n",
        "    json.dump(final_metrics, f, indent=2)\n",
        "\n",
        "print('Ensemble Test evaluation completed.')\n",
        "print(f\"Accuracy      : {final_acc:.4f}\")\n",
        "print(f\"Macro Precision: {final_macro_precision:.4f}\")\n",
        "print(f\"Macro Recall   : {final_macro_recall:.4f}\")\n",
        "print(f\"Macro F1       : {final_macro_f1:.4f}\")\n",
        "print(f\"Weighted F1    : {final_weighted_f1:.4f}\")"
    ]
    cell_16['source'] = cell_16_source

    # Cell 22: final summary
    cell_22 = nb['cells'][22]
    cell_22_source = [
        "# Compile learning rate tuning experiments dynamically (plan for grid search)\n",
        "print(\"=== LEARNING RATE GRID SEARCH EXPERIMENT PLAN ===\")\n",
        "print(f\"Target Learning Rates: {LR_EXPERIMENTS}\")\n",
        "print(f\"Selected Base LR     : {SELECTED_LR}\")\n",
        "print(f\"Weight Decay         : {WEIGHT_DECAY}\")\n",
        "print(f\"Classifier Dropout   : {CLASSIFIER_DROPOUT}\")\n",
        "print(f\"Label Smoothing      : {LABEL_SMOOTHING}\")\n",
        "print(f\"Model Name           : {MODEL_NAME}\")\n",
        "print(f\"Random Seed          : {RANDOM_STATE}\")\n",
        "print(f\"Timestamp            : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\")\n",
        "\n",
        "# To execute a learning rate experiment, you can loop over LR_EXPERIMENTS and run train_cross_validation(lr)\n",
        "print(\"\\n--- Running full tuning experiments (uncomment to execute) ---\")\n",
        "# lr_results = {}\n",
        "# for lr in LR_EXPERIMENTS:\n",
        "#     hist = train_cross_validation(lr)\n",
        "#     # Predict test ensemble accuracy\n",
        "#     # (Save fold weights to fold_{k}_lr_{lr}.bin)\n"
    ]
    cell_22['source'] = cell_22_source

    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(nb, f, indent=1, ensure_ascii=False)
    print("Successfully modified training notebook!")

modify_training()
