import json

def modify_training_v3():
    filepath = "02_finetuning_indobert_emotion2.ipynb"
    with open(filepath, 'r', encoding='utf-8') as f:
        nb = json.load(f)
    
    # Cell 2: Config and Hyperparameters
    cell_2 = nb['cells'][2]
    cell_2_source = [
        "import os\n",
        "import random\n",
        "import json\n",
        "import time\n",
        "import math\n",
        "import shutil\n",
        "import pandas as pd\n",
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "import seaborn as sns\n",
        "from tqdm.auto import tqdm\n",
        "from datetime import datetime\n",
        "from pathlib import Path\n",
        "\n",
        "import torch\n",
        "import torch.nn as nn\n",
        "from torch.utils.data import Dataset, DataLoader\n",
        "from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, f1_score, precision_score, recall_score, precision_recall_fscore_support\n",
        "from sklearn.model_selection import train_test_split\n",
        "from transformers import AutoTokenizer, BertForSequenceClassification, get_linear_schedule_with_warmup\n",
        "from torch.optim import AdamW\n",
        "\n",
        "# --- Reproducibility ---\n",
        "RANDOM_STATE = 42\n",
        "def set_seed(seed):\n",
        "    random.seed(seed)\n",
        "    np.random.seed(seed)\n",
        "    torch.manual_seed(seed)\n",
        "    torch.cuda.manual_seed_all(seed)\n",
        "    os.environ['PYTHONHASHSEED'] = str(seed)\n",
        "    torch.backends.cudnn.deterministic = True\n",
        "    torch.backends.cudnn.benchmark = False\n",
        "\n",
        "set_seed(RANDOM_STATE)\n",
        "\n",
        "# --- Hyperparameters ---\n",
        "MODEL_NAME = \"indobenchmark/indobert-base-p2\"\n",
        "MAX_LEN = 128\n",
        "BATCH_SIZE = 16\n",
        "EPOCHS = 10\n",
        "PATIENCE = 3\n",
        "NUM_LABELS = 2  # PIVOT: Klasifikasi Biner Sentimen (Positive vs Negative)\n",
        "WEIGHT_DECAY = 0.02\n",
        "WARMUP_RATIO = 0.1\n",
        "LABEL_SMOOTHING = 0.1\n",
        "CLASSIFIER_DROPOUT = 0.3\n",
        "FREEZE_LAYERS = 6  # Freeze the bottom 6 layers to prevent overfitting\n",
        "\n",
        "# Selected Learning Rate\n",
        "SELECTED_LR = 2e-5\n",
        "\n",
        "# --- Path Configuration ---\n",
        "try:\n",
        "    from google.colab import drive\n",
        "    IN_COLAB = True\n",
        "except ImportError:\n",
        "    IN_COLAB = False\n",
        "\n",
        "if IN_COLAB:\n",
        "    print(\"Running in Google Colab. Mounting Drive...\")\n",
        "    drive.mount('/content/drive')\n",
        "    BASE_PATH = \"/content/drive/MyDrive/xai_lime_vs_shap\"\n",
        "else:\n",
        "    print(\"Running locally.\")\n",
        "    BASE_PATH = \".\"\n",
        "\n",
        "TRAIN_DATA_PATH = f\"{BASE_PATH}/data/processed/prdect_train.csv\"\n",
        "TEST_DATA_PATH = f\"{BASE_PATH}/data/processed/prdect_test.csv\"\n",
        "MAPPING_PATH = f\"{BASE_PATH}/data/processed/prdect_label_map.json\"\n",
        "OUTPUT_DIR = f\"{BASE_PATH}/outputs/finetuning_indobert\"\n",
        "\n",
        "os.makedirs(OUTPUT_DIR, exist_ok=True)\n",
        "os.makedirs(f\"{OUTPUT_DIR}/model\", exist_ok=True)\n",
        "os.makedirs(f\"{OUTPUT_DIR}/plots\", exist_ok=True)\n",
        "os.makedirs(f\"{OUTPUT_DIR}/reports\", exist_ok=True)\n",
        "os.makedirs(f\"{OUTPUT_DIR}/tokenizer\", exist_ok=True)\n",
        "\n",
        "DEVICE = torch.device(\"cuda\" if torch.cuda.is_available() else \"cpu\")\n",
        "print(f\"Device used: {DEVICE}\")\n",
        "print(f\"Model name : {MODEL_NAME}\")\n",
        "\n",
        "# --- Label Mapping Loading ---\n",
        "if not os.path.exists(MAPPING_PATH):\n",
        "    MAPPING_PATH = f\"{BASE_PATH}/data/processed/prdect_label_map.json\"\n",
        "\n",
        "if os.path.exists(MAPPING_PATH):\n",
        "    with open(MAPPING_PATH, 'r') as f:\n",
        "        mapping_data = json.load(f)\n",
        "    LABEL_MAP = mapping_data.get('label2id', {'negative': 0, 'positive': 1})\n",
        "    LABEL_MAP = {k.lower().strip(): int(v) for k, v in LABEL_MAP.items()}\n",
        "    ID2LABEL = {int(k): v.lower().strip() for k, v in mapping_data.get('id2label', {'0': 'negative', '1': 'positive'}).items()}\n",
        "else:\n",
        "    LABEL_MAP = {'negative': 0, 'positive': 1}\n",
        "    ID2LABEL = {0: 'negative', 1: 'positive'}\n",
        "\n",
        "LABEL_ORDER = [ID2LABEL[i] for i in sorted(ID2LABEL.keys())]\n",
        "EMOTION_MAP = LABEL_MAP\n",
        "ID2EMOTION = ID2LABEL"
    ]
    cell_2['source'] = cell_2_source

    # Cell 10: Model Initialization helper function with layer freezing
    cell_10 = nb['cells'][10]
    cell_10_source = [
        "def initialize_model(model_name, num_labels, dropout_prob, freeze_layers=6):\n",
        "    model = BertForSequenceClassification.from_pretrained(\n",
        "        model_name,\n",
        "        num_labels=num_labels\n",
        "    )\n",
        "    # Set custom classification dropout\n",
        "    model.config.classifier_dropout = dropout_prob\n",
        "    \n",
        "    # Freeze the bottom N encoder layers to prevent overfitting\n",
        "    if freeze_layers > 0:\n",
        "        print(f\"Freezing embeddings and bottom {freeze_layers} encoder layers...\")\n",
        "        for param in model.bert.embeddings.parameters():\n",
        "            param.requires_grad = False\n",
        "        for layer_idx in range(freeze_layers):\n",
        "            for param in model.bert.encoder.layer[layer_idx].parameters():\n",
        "                param.requires_grad = False\n",
        "                \n",
        "    model = model.to(DEVICE)\n",
        "    return model\n",
        "\n",
        "model = initialize_model(MODEL_NAME, NUM_LABELS, CLASSIFIER_DROPOUT, FREEZE_LAYERS)\n",
        "\n",
        "# Verify parameters\n",
        "trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)\n",
        "total_params = sum(p.numel() for p in model.parameters())\n",
        "print(f\"Total Parameters    : {total_params:,}\")\n",
        "print(f\"Trainable Parameters: {trainable_params:,}\")"
    ]
    cell_10['source'] = cell_10_source

    # Cell 14: Execution: 5-Fold Cross Validation training loop with early stopping on val_loss
    cell_14 = nb['cells'][14]
    cell_14_source = [
        "def train_cross_validation(learning_rate):\n",
        "    print(f\"==================================================\")\n",
        "    print(f\"STARTING 5-FOLD CROSS VALIDATION WITH LR = {learning_rate}\")\n",
        "    print(f\"==================================================\")\n",
        "    \n",
        "    cv_history = []\n",
        "    start_time = time.time()\n",
        "    \n",
        "    for fold_idx in range(5):\n",
        "        print(f\"\\n--- Fold {fold_idx + 1} / 5 ---\")\n",
        "        \n",
        "        # Split train and validation dynamically based on fold column\n",
        "        fold_train_df = train_df[train_df['fold'] != fold_idx].reset_index(drop=True)\n",
        "        fold_val_df = train_df[train_df['fold'] == fold_idx].reset_index(drop=True)\n",
        "        \n",
        "        fold_train_loader = create_data_loader(fold_train_df, tokenizer, MAX_LEN, BATCH_SIZE)\n",
        "        fold_val_loader = create_data_loader(fold_val_df, tokenizer, MAX_LEN, BATCH_SIZE, shuffle=False)\n",
        "        \n",
        "        # Initialize model, optimizer, scheduler for this fold\n",
        "        fold_model = initialize_model(MODEL_NAME, NUM_LABELS, CLASSIFIER_DROPOUT, FREEZE_LAYERS)\n",
        "        fold_optimizer = AdamW(fold_model.parameters(), lr=learning_rate, weight_decay=WEIGHT_DECAY)\n",
        "        \n",
        "        total_steps = len(fold_train_loader) * EPOCHS\n",
        "        warmup_steps = max(1, int(total_steps * WARMUP_RATIO))\n",
        "        fold_scheduler = get_linear_schedule_with_warmup(\n",
        "            fold_optimizer,\n",
        "            num_warmup_steps=warmup_steps,\n",
        "            num_training_steps=total_steps\n",
        "        )\n",
        "        \n",
        "        best_val_loss = float('inf')\n",
        "        patience_counter = 0\n",
        "        fold_best_path = f\"{OUTPUT_DIR}/model/best_model_fold_{fold_idx}.bin\"\n",
        "        \n",
        "        fold_history = {\n",
        "            'epoch': [],\n",
        "            'train_loss': [], 'train_acc': [],\n",
        "            'val_loss': [], 'val_acc': []\n",
        "        }\n",
        "        \n",
        "        for epoch in range(EPOCHS):\n",
        "            print(f\"Epoch {epoch + 1}/{EPOCHS}\")\n",
        "            \n",
        "            # Train epoch\n",
        "            train_acc, train_loss, train_metrics = train_epoch(\n",
        "                fold_model, fold_train_loader, loss_fn, fold_optimizer, DEVICE, fold_scheduler, len(fold_train_df)\n",
        "            )\n",
        "            \n",
        "            # Val epoch\n",
        "            val_acc, val_loss, val_metrics, _, _ = eval_model(\n",
        "                fold_model, fold_val_loader, loss_fn, DEVICE, len(fold_val_df)\n",
        "            )\n",
        "            \n",
        "            print(\n",
        "                f\"Train loss: {train_loss:.4f} acc: {train_acc:.4f} | \"\n",
        "                f\"Val loss: {val_loss:.4f} acc: {val_acc:.4f} | \"\n",
        "                f\"Best Val Loss: {best_val_loss:.4f} | Patience: {patience_counter}/{PATIENCE}\"\n",
        "            )\n",
        "            \n",
        "            fold_history['epoch'].append(epoch + 1)\n",
        "            fold_history['train_loss'].append(train_loss)\n",
        "            fold_history['train_acc'].append(train_acc.item())\n",
        "            fold_history['val_loss'].append(val_loss)\n",
        "            fold_history['val_acc'].append(val_acc.item())\n",
        "            \n",
        "            # Early stopping monitors val_loss\n",
        "            if val_loss < best_val_loss:\n",
        "                torch.save(fold_model.state_dict(), fold_best_path)\n",
        "                best_val_loss = val_loss\n",
        "                patience_counter = 0\n",
        "            else:\n",
        "                patience_counter += 1\n",
        "                \n",
        "            if patience_counter >= PATIENCE:\n",
        "                print(f\"Early stopping triggered for Fold {fold_idx + 1} at epoch {epoch + 1}.\")\n",
        "                break\n",
        "                \n",
        "        cv_history.append(fold_history)\n",
        "        \n",
        "    end_time = time.time()\n",
        "    print(f\"\\nCross-validation completed in {(end_time - start_time)/60:.2f} minutes.\")\n",
        "    \n",
        "    # Save history as JSON file\n",
        "    history_json_path = f\"{OUTPUT_DIR}/reports/training_history.json\"\n",
        "    with open(history_json_path, 'w') as f:\n",
        "        json.dump(cv_history, f, indent=2)\n",
        "    print(f\"Saved cross-validation training history to: {history_json_path}\")\n",
        "    \n",
        "    return cv_history\n",
        "\n",
        "# Execute 5-fold cross validation for the selected learning rate\n",
        "cv_results = train_cross_validation(SELECTED_LR)"
    ]
    cell_14['source'] = cell_14_source

    # Cell 16: Evaluation & Academic Visualization
    cell_16 = nb['cells'][16]
    cell_16_source = [
        "# --- ACADEMIC VISUALIZATION: LOSS & ACCURACY CURVES ---\n",
        "max_epochs = max(len(fh['epoch']) for fh in cv_results)\n",
        "epochs_range = list(range(1, max_epochs + 1))\n",
        "\n",
        "# Align fold histories for averaging (pad with final epoch values in case of early stopping)\n",
        "aligned_train_losses = []\n",
        "aligned_val_losses = []\n",
        "aligned_train_accs = []\n",
        "aligned_val_accs = []\n",
        "\n",
        "for fh in cv_results:\n",
        "    t_loss = fh['train_loss'] + [fh['train_loss'][-1]] * (max_epochs - len(fh['train_loss']))\n",
        "    v_loss = fh['val_loss'] + [fh['val_loss'][-1]] * (max_epochs - len(fh['val_loss']))\n",
        "    t_acc  = fh['train_acc'] + [fh['train_acc'][-1]] * (max_epochs - len(fh['train_acc']))\n",
        "    v_acc  = fh['val_acc'] + [fh['val_acc'][-1]] * (max_epochs - len(fh['val_acc']))\n",
        "    aligned_train_losses.append(t_loss)\n",
        "    aligned_val_losses.append(v_loss)\n",
        "    aligned_train_accs.append(t_acc)\n",
        "    aligned_val_accs.append(v_acc)\n",
        "\n",
        "mean_train_loss = np.mean(aligned_train_losses, axis=0)\n",
        "mean_val_loss   = np.mean(aligned_val_losses, axis=0)\n",
        "mean_train_acc  = np.mean(aligned_train_accs, axis=0)\n",
        "mean_val_acc    = np.mean(aligned_val_accs, axis=0)\n",
        "\n",
        "plt.figure(figsize=(12, 5), dpi=300)\n",
        "\n",
        "# Plot Loss\n",
        "plt.subplot(1, 2, 1)\n",
        "for i, fh in enumerate(cv_results):\n",
        "    plt.plot(fh['epoch'], fh['train_loss'], color='blue', alpha=0.15, linestyle='--')\n",
        "    plt.plot(fh['epoch'], fh['val_loss'], color='orange', alpha=0.15, linestyle='--')\n",
        "plt.plot(epochs_range, mean_train_loss, color='blue', label='Mean Train Loss', linewidth=2)\n",
        "plt.plot(epochs_range, mean_val_loss, color='orange', label='Mean Val Loss', linewidth=2)\n",
        "plt.title('Loss Curves (5 Folds)', fontsize=12, fontweight='bold')\n",
        "plt.xlabel('Epoch', fontsize=10)\n",
        "plt.ylabel('Loss', fontsize=10)\n",
        "plt.grid(True, linestyle=':', alpha=0.6)\n",
        "plt.legend(frameon=True, fontsize=9)\n",
        "\n",
        "# Plot Accuracy\n",
        "plt.subplot(1, 2, 2)\n",
        "for i, fh in enumerate(cv_results):\n",
        "    plt.plot(fh['epoch'], fh['train_acc'], color='blue', alpha=0.15, linestyle='--')\n",
        "    plt.plot(fh['epoch'], fh['val_acc'], color='orange', alpha=0.15, linestyle='--')\n",
        "plt.plot(epochs_range, mean_train_acc, color='blue', label='Mean Train Acc', linewidth=2)\n",
        "plt.plot(epochs_range, mean_val_acc, color='orange', label='Mean Val Acc', linewidth=2)\n",
        "plt.title('Accuracy Curves (5 Folds)', fontsize=12, fontweight='bold')\n",
        "plt.xlabel('Epoch', fontsize=10)\n",
        "plt.ylabel('Accuracy', fontsize=10)\n",
        "plt.grid(True, linestyle=':', alpha=0.6)\n",
        "plt.legend(frameon=True, fontsize=9)\n",
        "\n",
        "plt.tight_layout()\n",
        "plt.savefig(f\"{OUTPUT_DIR}/plots/training_curves.png\", bbox_inches='tight')\n",
        "plt.show()\n",
        "\n",
        "def get_predictions(model, data_loader):\n",
        "    model = model.eval()\n",
        "    review_texts = []\n",
        "    predictions = []\n",
        "    prediction_probs = []\n",
        "    real_values = []\n",
        "\n",
        "    with torch.no_grad():\n",
        "        for d in data_loader:\n",
        "            texts = d[\"review_text\"]\n",
        "            input_ids = d[\"input_ids\"].to(DEVICE)\n",
        "            attention_mask = d[\"attention_mask\"].to(DEVICE)\n",
        "            labels = d[\"labels\"].to(DEVICE)\n",
        "\n",
        "            outputs = model(\n",
        "                input_ids=input_ids,\n",
        "                attention_mask=attention_mask\n",
        "            )\n",
        "\n",
        "            logits = outputs.logits\n",
        "            probs = torch.nn.functional.softmax(logits, dim=1)\n",
        "            _, preds = torch.max(logits, dim=1)\n",
        "\n",
        "            review_texts.extend(texts)\n",
        "            predictions.extend(preds.detach().cpu().tolist())\n",
        "            prediction_probs.extend(probs.detach().cpu().tolist())\n",
        "            real_values.extend(labels.detach().cpu().tolist())\n",
        "\n",
        "    predictions = torch.tensor(predictions)\n",
        "    prediction_probs = torch.tensor(prediction_probs)\n",
        "    real_values = torch.tensor(real_values)\n",
        "    return review_texts, predictions, prediction_probs, real_values\n",
        "\n",
        "# Final Evaluation on Test Set uses the ensemble of all 5 folds\n",
        "print(\"Evaluating 5-fold ensemble model on the test set...\")\n",
        "y_pred_probs_list = []\n",
        "y_test_check = None\n",
        "y_review_texts = None\n",
        "\n",
        "for fold_idx in range(5):\n",
        "    fold_model_path = f\"{OUTPUT_DIR}/model/best_model_fold_{fold_idx}.bin\"\n",
        "    fold_model = initialize_model(MODEL_NAME, NUM_LABELS, CLASSIFIER_DROPOUT, FREEZE_LAYERS)\n",
        "    fold_model.load_state_dict(torch.load(fold_model_path, map_location=DEVICE))\n",
        "    \n",
        "    review_texts, y_pred_fold, y_pred_probs_fold, y_test_fold = get_predictions(fold_model, test_data_loader)\n",
        "    y_pred_probs_list.append(y_pred_probs_fold)\n",
        "    y_test_check = y_test_fold\n",
        "    y_review_texts = review_texts\n",
        "\n",
        "# Average probabilities across the 5 folds (Ensemble prediction)\n",
        "y_pred_probs = torch.mean(torch.stack(y_pred_probs_list), dim=0)\n",
        "y_pred = torch.argmax(y_pred_probs, dim=1)\n",
        "y_test = y_test_check\n",
        "\n",
        "print(\"\\n\" + \"=\"*60 + \"\\nTABEL HASIL MODEL UNTUK LAPORAN SKRIPSI\\n\" + \"=\"*60)\n",
        "\n",
        "# --- TABEL 4: Classification Report Table ---\n",
        "class_names = [ID2EMOTION[i] for i in range(NUM_LABELS)]\n",
        "report = classification_report(y_test, y_pred, target_names=class_names, digits=4, zero_division=0)\n",
        "print(\"\\n### TABEL 4: TEXT CLASSIFICATION REPORT (ENSEMBLE MODEL ON TEST SET)\")\n",
        "print(report)\n",
        "\n",
        "report_dict = classification_report(y_test, y_pred, target_names=class_names, output_dict=True, zero_division=0)\n",
        "report_df = pd.DataFrame(report_dict).T\n",
        "report_df = report_df.round(4)\n",
        "print(report_df.to_markdown())\n",
        "\n",
        "pd.DataFrame(report_dict).T.to_csv(f\"{OUTPUT_DIR}/reports/classification_report.csv\")\n",
        "with open(f\"{OUTPUT_DIR}/reports/classification_report.txt\", \"w\") as f:\n",
        "    f.write(report)\n",
        "\n",
        "# --- TABEL 5: Confusion Matrix Table & Heatmap ---\n",
        "cm = confusion_matrix(y_test, y_pred)\n",
        "df_cm = pd.DataFrame(cm, index=class_names, columns=class_names)\n",
        "print(\"\\n### TABEL 5: CONFUSION MATRIX (RAW COUNTS)\")\n",
        "print(df_cm.to_markdown())\n",
        "\n",
        "cm_normalized = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]\n",
        "plt.figure(figsize=(7, 6), dpi=300)\n",
        "annot_labels = np.empty_like(cm, dtype=object)\n",
        "for i in range(cm.shape[0]):\n",
        "    for j in range(cm.shape[1]):\n",
        "        annot_labels[i, j] = f\"{cm[i, j]}\\n({cm_normalized[i, j]*100:.1f}%)\"\n",
        "\n",
        "sns.heatmap(\n",
        "    cm_normalized, \n",
        "    annot=annot_labels, \n",
        "    fmt='', \n",
        "    cmap='Blues', \n",
        "    xticklabels=class_names, \n",
        "    yticklabels=class_names,\n",
        "    annot_kws={\"size\": 11, \"weight\": \"bold\"},\n",
        "    cbar=True\n",
        ")\n",
        "plt.title(\"Normalized Confusion Matrix (Ensemble Model)\", fontsize=13, fontweight='bold', pad=15)\n",
        "plt.xlabel(\"Predicted Label\", fontsize=11, labelpad=10)\n",
        "plt.ylabel(\"Actual Label\", fontsize=11, labelpad=10)\n",
        "plt.xticks(fontsize=10)\n",
        "plt.yticks(fontsize=10, rotation=0)\n",
        "plt.tight_layout()\n",
        "plt.savefig(f\"{OUTPUT_DIR}/plots/confusion_matrix.png\", bbox_inches='tight')\n",
        "plt.show()\n",
        "\n",
        "final_acc = accuracy_score(y_test, y_pred)\n",
        "final_macro_precision = precision_score(y_test, y_pred, average='macro', zero_division=0)\n",
        "final_macro_recall = recall_score(y_test, y_pred, average='macro', zero_division=0)\n",
        "final_macro_f1 = f1_score(y_test, y_pred, average='macro', zero_division=0)\n",
        "final_weighted_f1 = f1_score(y_test, y_pred, average='weighted', zero_division=0)\n",
        "\n",
        "final_metrics = {\n",
        "    'test_accuracy': final_acc,\n",
        "    'test_macro_precision': final_macro_precision,\n",
        "    'test_macro_recall': final_macro_recall,\n",
        "    'test_macro_f1': final_macro_f1,\n",
        "    'test_weighted_f1': final_weighted_f1,\n",
        "}\n",
        "with open(f\"{OUTPUT_DIR}/reports/test_metrics.json\", \"w\") as f:\n",
        "    json.dump(final_metrics, f, indent=2)\n",
        "\n",
        "print(\"\\n\" + \"=\"*60)\n",
        "print('Ensemble Test evaluation completed.')\n",
        "print(f\"Accuracy      : {final_acc:.4f}\")\n",
        "print(f\"Macro Precision: {final_macro_precision:.4f}\")\n",
        "print(f\"Macro Recall   : {final_macro_recall:.4f}\")\n",
        "print(f\"Macro F1       : {final_macro_f1:.4f}\")\n",
        "print(f\"Weighted F1    : {final_weighted_f1:.4f}\")\n",
        "print(\"=\"*60)"
    ]
    cell_16['source'] = cell_16_source

    # Cell 18: Error Analysis
    cell_18 = nb['cells'][18]
    cell_18_source = [
        "error_df = pd.DataFrame({\n",
        "    'review_text': y_review_texts,\n",
        "    'true_labels': y_test.tolist(),\n",
        "    'pred_labels': y_pred.tolist(),\n",
        "    'confidence': [probs[pred].item() for probs, pred in zip(y_pred_probs, y_pred)]\n",
        "})\n",
        "\n",
        "# Filter only errors\n",
        "errors = error_df[error_df['true_labels'] != error_df['pred_labels']].copy()\n",
        "\n",
        "# Map back to names\n",
        "errors['true_emotion'] = errors['true_labels'].map(ID2EMOTION)\n",
        "errors['pred_emotion'] = errors['pred_labels'].map(ID2EMOTION)\n",
        "\n",
        "print(\"\\n\" + \"=\"*60 + \"\\nANALISIS KESALAHAN (ERROR ANALYSIS) UNTUK LAPORAN SKRIPSI\\n\" + \"=\"*60)\n",
        "\n",
        "# --- TABEL 6: Top 10 High-Confidence Errors ---\n",
        "print(\"\\n### TABEL 6: CONTOH 10 KASUS SALAH KLASIFIKASI DENGAN CONFIDENCE TINGGI\")\n",
        "display_df = errors.sort_values(by='confidence', ascending=False).head(10)\n",
        "print(display_df[['review_text', 'true_emotion', 'pred_emotion', 'confidence']].to_markdown(index=False))\n",
        "print(\"-\" * 60)\n",
        "\n",
        "# --- TABEL 7: Misclassification Pattern ---\n",
        "error_pattern = errors.groupby(['true_emotion', 'pred_emotion']).size().reset_index(name='count')\n",
        "error_pattern = error_pattern.sort_values(by='count', ascending=False)\n",
        "print(\"\\n### TABEL 7: POLA SALAH KLASIFIKASI (ERROR PATTERNS)\")\n",
        "print(error_pattern.to_markdown(index=False))\n",
        "print(\"=\"*60)\n",
        "\n",
        "# Ensure the reports directory exists before saving\n",
        "os.makedirs(f\"{OUTPUT_DIR}/reports\", exist_ok=True)\n",
        "\n",
        "# Save Error Report\n",
        "errors.to_csv(f\"{OUTPUT_DIR}/reports/error_analysis.csv\", index=False)"
    ]
    cell_18['source'] = cell_18_source

    # Cell 20: Save Model & Tokenizer
    cell_20 = nb['cells'][20]
    cell_20_source = [
        "# Save Final Model and Tokenizer\n",
        "model.save_pretrained(f\"{OUTPUT_DIR}/model/final_indobert_sentiment\")\n",
        "tokenizer.save_pretrained(f\"{OUTPUT_DIR}/tokenizer/indobert_tokenizer\")\n",
        "\n",
        "# Determine the best model path from cross-validation results\n",
        "overall_best_val_loss = float('inf')\n",
        "best_fold_idx = -1\n",
        "\n",
        "for idx, fold_history in enumerate(cv_results):\n",
        "    # Find the minimum validation loss achieved in this specific fold\n",
        "    min_val_loss_in_fold = min(fold_history['val_loss'])\n",
        "    if min_val_loss_in_fold < overall_best_val_loss:\n",
        "        overall_best_val_loss = min_val_loss_in_fold\n",
        "        best_fold_idx = idx\n",
        "\n",
        "best_model_path = f\"{OUTPUT_DIR}/model/best_model_fold_{best_fold_idx}.bin\"\n",
        "shutil.copy2(best_model_path, f\"{OUTPUT_DIR}/model/best_model.bin\")\n",
        "\n",
        "# Copy the best fold parameters as the final model binary for inference\n",
        "shutil.copy2(best_model_path, f\"{OUTPUT_DIR}/model/final_indobert_sentiment/pytorch_model.bin\")\n",
        "\n",
        "# Save Training History\n",
        "with open(f\"{OUTPUT_DIR}/reports/training_history.json\", \"w\") as f:\n",
        "    json.dump(cv_results, f, indent=2)\n",
        "\n",
        "print(f\"All assets saved to: {OUTPUT_DIR}\")"
    ]
    cell_20['source'] = cell_20_source

    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(nb, f, indent=1, ensure_ascii=False)
    print("Successfully modified training notebook for Academic Sentiment Classification!")

if __name__ == "__main__":
    modify_training_v3()
